Repository cacic-fct/fct-app, pull requests merged in 2022-10, with the labels that each got.

#53 List subscriptions and payments
  src/app/app-routing.module.ts
  src/app/page-subscriptions-payments/page-pay/page-pay-routing.module.ts
  src/app/page-subscriptions-payments/page-pay/page-pay.module.ts
  src/app/page-subscriptions-payments/page-pay/page-pay.page.html
  src/app/page-subscriptions-payments/page-pay/page-pay.page.scss
  src/app/page-subscriptions-payments/page-pay/page-pay.page.spec.ts
  src/app/page-subscriptions-payments/page-pay/page-pay.page.ts
  src/app/page-subscriptions-payments/page-subscriptions-routing.module.ts
  src/app/page-subscriptions-payments/page-subscriptions.module.ts
  src/app/page-subscriptions-payments/page-subscriptions.page.html
  src/app/page-subscriptions-payments/page-subscriptions.page.scss
  src/app/page-subscriptions-payments/page-subscriptions.page.spec.ts
  src/app/page-subscriptions-payments/page-subscriptions.page.ts
  src/app/tab-menu/tab-menu.page.html
Labels: enhancement

#74 Refactor subscription page
  src/app/page-subscription/page-subscription.page.ts
Labels: bug, hacktoberfest-accepted

#67 Add receipt validation page
  .gitignore
  firebase.json
  src/app/app.module.ts
  src/app/page-restricted-area/page-manage-major-events/page-manage-major-events-routing.module.ts
  src/app/page-restricted-area/page-manage-major-events/page-manage-major-events.page.html
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt-routing.module.ts
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt.module.ts
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt.page.html
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt.page.scss
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt.page.spec.ts
  src/app/page-restricted-area/page-manage-major-events/validate-receipt/validate-receipt.page.ts
  src/app/page-subscriptions-payments/page-pay/page-pay.page.ts
Labels: enhancement

#75 Add close modal button and SMS countdown
  src/app/page-verify-phone/page-verify-phone.page.html
  src/app/page-verify-phone/page-verify-phone.page.ts
Labels: enhancement, hacktoberfest-accepted

#73 Add online attendance page
  src/app/app-routing.module.ts
  src/app/page-confirm-attendance/page-confirm-attendance-routing.module.ts
  src/app/page-confirm-attendance/page-confirm-attendance.html
  src/app/page-confirm-attendance/page-confirm-attendance.module.ts
  src/app/page-confirm-attendance/page-confirm-attendance.scss
  src/app/page-confirm-attendance/page-confirm-attendance.spec.ts
  src/app/page-confirm-attendance/page-confirm-attendance.ts
  src/app/shared/services/auth.service.ts
  src/app/shared/services/event.ts
  src/app/shared/services/user.ts
Labels: enhancement, hacktoberfest-accepted

#77 Add event subscription button
  src/app/page-subscription/page-subscription.page.ts
  src/app/page-subscriptions-payments/page-subscriptions.page.html
  src/app/page-subscriptions-payments/page-subscriptions.page.ts
  src/app/shared/services/event.ts
  src/app/tab-calendar/page-calendar-event/page-calendar-event.page.html
  src/app/tab-calendar/page-calendar-event/page-calendar-event.page.ts
Labels: enhancement, hacktoberfest-accepted

#79 Workaround firestore 10 elements limit
  src/app/page-subscription/page-subscription.page.ts
Labels: bug, enhancement, hacktoberfest-accepted

#84 Allow users to edit their subscriptions
  src/app/page-subscription/page-subscription.page.html
  src/app/page-subscription/page-subscription.page.ts
  src/app/page-subscriptions-payments/page-pay/page-pay.page.html
  src/app/page-subscriptions-payments/page-pay/page-pay.page.scss
  src/app/page-subscriptions-payments/page-subscriptions.page.html
  src/app/tab-events/tab-events.page.html
Labels: enhancement
